server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  default:
    host: "localhost" # 地址
    port: "3306" # 端口
    user: "root" # 账号
    pass: "123456" # 密码
#    pass: "mysql" # 密码
    name: "kbgo" # 数据库名称
    type: "mysql" # 数据库类型
    charset: "utf8mb4" # 数据库编码，一定要加上，因为文档里面经常出现特殊字符

# Milvus向量数据库配置
milvus:
  address: "http://www.sgxlllm.cn:19530"
  database: "kbgo"
  dim: 1024
  metricType: "COSINE"  # 向量相似度度量类型: COSINE(余弦相似度), L2(欧式距离), IP(内积), 默认 COSINE

# rustfs文件存储配置
rustfs:
  endpoint: "www.sgxlllm.cn:9000"
  accessKey: "gOlxd2a38wUyAeI1rtKD"
  secretKey: "7CbIT6yV9mJReQYzkZhdE83Sq2LonGpD051PAa4X"
  bucketName: "kbfiles"
  ssl: false

embedding:
  apiKey: "sk-jAkmV1jA7EMZQL9JutGNS48Z9DlwHVw3NpnDsOFkvr85hQjH"
  baseURL: "https://api.agicto.cn/v1"
  model: "text-embedding-v3"

rerank:
  apiKey: "sk-jAkmV1jA7EMZQL9JutGNS48Z9DlwHVw3NpnDsOFkvr85hQjH"
  baseURL: "https://api.agicto.cn/v1"
  model: "gte-rerank-v2"

rewrite:
  apiKey: "sk-jAkmV1jA7EMZQL9JutGNS48Z9DlwHVw3NpnDsOFkvr85hQjH"
  baseURL: "https://api.agicto.cn/v1"
  model: "qwen3-32b" # 测试下来14b速度最快

qa:
  apiKey: "sk-jAkmV1jA7EMZQL9JutGNS48Z9DlwHVw3NpnDsOFkvr85hQjH"
  baseURL: "https://api.agicto.cn/v1"
  model: "qwen3-32b" # 测试下来14b速度最快

chat:
  apiKey: "sk-jAkmV1jA7EMZQL9JutGNS48Z9DlwHVw3NpnDsOFkvr85hQjH"
  baseURL: "https://api.agicto.cn/v1"
  model: "qwen3-32b"
